apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: $GRAFANA_DB_USER
    editable: false
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      database: $GRAFANA_DB_NAME
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
      maxOpenConns: 3
      maxIdleConns: 1
      maxIdleConnsAuto: false
      connMaxLifetime: 14400