global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: equipment-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3000